package domaindocs4s.architecture

// ============================================================================
// External Spec Examples
//
// These show the JSON that each service would generate and upload to the
// central repository. The aggregation tool reads all specs and produces
// the system-level view.
//
// Key differences from previous version:
//   - No separate id/name/metadata — artifact fields carry everything
//   - gRPC is per-endpoint (per method), not per-service
//   - matchKey is derived from artifact fields, used for cross-service matching
// ============================================================================

object ExternalSpecs {

  // Generated by: LedgerServiceFlow.flow.externalSpec("ledger", "Financial Ledger Service")
  val ledgerServiceSpecJson: String =
    """{
      |  "service": {
      |    "id": "ledger",
      |    "name": "Financial Ledger Service"
      |  },
      |  "produced": [
      |    {
      |      "type": "kafka-topic",
      |      "topicName": "ledger.movements"
      |    },
      |    {
      |      "type": "kafka-topic",
      |      "topicName": "ledger.legal-entity-changes"
      |    },
      |    {
      |      "type": "database-table",
      |      "database": "operational_projections",
      |      "schema": "ledger",
      |      "tableName": "movements"
      |    },
      |    {
      |      "type": "database-table",
      |      "database": "operational_projections",
      |      "schema": "ledger",
      |      "tableName": "account_balances"
      |    },
      |    {
      |      "type": "database-table",
      |      "database": "operational_projections",
      |      "schema": "ledger",
      |      "tableName": "operator_closing_of_account"
      |    },
      |    {
      |      "type": "grpc-endpoint",
      |      "serviceName": "LedgerServiceAPI",
      |      "methodName": "GetUserBalance"
      |    },
      |    {
      |      "type": "grpc-endpoint",
      |      "serviceName": "LedgerServiceAPI",
      |      "methodName": "RecordUserDeposit"
      |    },
      |    {
      |      "type": "s3-location",
      |      "bucket": "ledger-exports",
      |      "prefix": "assets/"
      |    }
      |  ],
      |  "consumed": [
      |    {
      |      "type": "grpc-endpoint",
      |      "serviceName": "RateServiceAPI",
      |      "methodName": "GetRate"
      |    },
      |    {
      |      "type": "grpc-endpoint",
      |      "serviceName": "ConfigServiceAPI",
      |      "methodName": "GetCurrencyInventory"
      |    }
      |  ]
      |}""".stripMargin

  // Generated by: ControllingServiceFlow.flow.externalSpec("controlling", "Controlling Service")
  val controllingServiceSpecJson: String =
    """{
      |  "service": {
      |    "id": "controlling",
      |    "name": "Controlling Service"
      |  },
      |  "produced": [
      |    {
      |      "type": "http-endpoint",
      |      "method": "POST",
      |      "path": "/reports/generate"
      |    },
      |    {
      |      "type": "database-table",
      |      "database": "operational_projections",
      |      "schema": "controlling",
      |      "tableName": "cashflow_method"
      |    }
      |  ],
      |  "consumed": [
      |    {
      |      "type": "grpc-endpoint",
      |      "serviceName": "LedgerServicePrivateAPI",
      |      "methodName": "GetBalances"
      |    },
      |    {
      |      "type": "grpc-endpoint",
      |      "serviceName": "RateServiceAPI",
      |      "methodName": "GetRate"
      |    },
      |    {
      |      "type": "grpc-endpoint",
      |      "serviceName": "ConfigServiceAPI",
      |      "methodName": "GetCurrencyInventory"
      |    },
      |    {
      |      "type": "database-table",
      |      "database": "operational_projections",
      |      "schema": "ledger",
      |      "tableName": "operator_closing_of_account"
      |    },
      |    {
      |      "type": "spreadsheet",
      |      "provider": "Google Sheets"
      |    }
      |  ]
      |}""".stripMargin
}
